# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BasicIntegration' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BasicIntegration
	
	# Pods for Firebase
        pod 'Firebase/Analytics'
        pod 'Firebase/Core'
        pod 'Firebase/Auth'
        pod 'Firebase/Firestore'
        pod 'Firebase/Storage'
        pod 'SDWebImage', '~> 5.0'

	# Optionally, include the Swift extensions if you're using Swift.
        pod 'FirebaseFirestoreSwift'
end
